from __future__ import annotations

import re
from typing import Final

MECHANISM_DOMAINS: Final[tuple[str, ...]] = (
    "VALUATION",
    "QUALITY_PROFITABILITY",
    "ORDER_FLOW",
    "CAPITALIZATION",
    "TURNOVER_LIQUIDITY",
    "PRICE_REVERSAL",
    "MOMENTUM_TREND",
    "VOLATILITY_RISK",
    "OTHER_INTERPRETABLE",
)

_ALIASES: Final[dict[str, str]] = {
    "VALUE": "VALUATION",
    "VALUATION_VALUE": "VALUATION",
    "FUNDAMENTAL_VALUE": "VALUATION",
    "FUNDAMENTAL_VALUATION": "VALUATION",
    "BOOK_TO_PRICE": "VALUATION",
    "PB_PE": "VALUATION",
    "QUALITY": "QUALITY_PROFITABILITY",
    "PROFITABILITY": "QUALITY_PROFITABILITY",
    "QUALITY_PROFITABILITY": "QUALITY_PROFITABILITY",
    "ROE_QUALITY": "QUALITY_PROFITABILITY",
    "ORDERFLOW": "ORDER_FLOW",
    "MONEY_FLOW": "ORDER_FLOW",
    "CAPITAL_FLOW": "ORDER_FLOW",
    "MAIN_FORCE_FLOW": "ORDER_FLOW",
    "NORTHBOUND_FLOW": "ORDER_FLOW",
    "SIZE": "CAPITALIZATION",
    "MARKET_CAP": "CAPITALIZATION",
    "MARKET_CAPITALIZATION": "CAPITALIZATION",
    "FLOAT_CAP": "CAPITALIZATION",
    "FREE_FLOAT": "CAPITALIZATION",
    "CAPITAL_SUPPLY": "CAPITALIZATION",
    "LIQUIDITY": "TURNOVER_LIQUIDITY",
    "LIQUIDITY_ACTIVITY": "TURNOVER_LIQUIDITY",
    "TURNOVER": "TURNOVER_LIQUIDITY",
    "TURNOVER_ACTIVITY": "TURNOVER_LIQUIDITY",
    "VOLUME": "TURNOVER_LIQUIDITY",
    "VOLUME_ACTIVITY": "TURNOVER_LIQUIDITY",
    "DOLLAR_VOLUME": "TURNOVER_LIQUIDITY",
    "AMOUNT_LIQUIDITY": "TURNOVER_LIQUIDITY",
    "PRICE_REVERSION": "PRICE_REVERSAL",
    "REVERSAL": "PRICE_REVERSAL",
    "MEAN_REVERSION": "PRICE_REVERSAL",
    "MEAN_REVERTING": "PRICE_REVERSAL",
    "SHORT_TERM_REVERSAL": "PRICE_REVERSAL",
    "MOMENTUM": "MOMENTUM_TREND",
    "PRICE_TREND": "MOMENTUM_TREND",
    "TREND": "MOMENTUM_TREND",
    "TREND_FOLLOWING": "MOMENTUM_TREND",
    "BREAKOUT": "MOMENTUM_TREND",
    "VOLATILITY": "VOLATILITY_RISK",
    "VOL": "VOLATILITY_RISK",
    "RISK": "VOLATILITY_RISK",
    "VARIANCE": "VOLATILITY_RISK",
    "DOWNSIDE_RISK": "VOLATILITY_RISK",
    "OTHER": "OTHER_INTERPRETABLE",
    "UNKNOWN": "OTHER_INTERPRETABLE",
    "INTERPRETABLE_OTHER": "OTHER_INTERPRETABLE",
    "PRICE_ACTION": "OTHER_INTERPRETABLE",
}


def normalize_mechanism(value: object, *, default: str = "OTHER_INTERPRETABLE") -> str:
    """Normalize mechanism labels to the controlled institutional enum."""
    fallback = default if default in MECHANISM_DOMAINS or default == "" else "OTHER_INTERPRETABLE"
    raw = str(value or "").strip()
    if not raw:
        return fallback
    key = re.sub(r"[^0-9A-Za-z]+", "_", raw).strip("_").upper()
    if not key:
        return fallback
    if key in MECHANISM_DOMAINS:
        return key
    return _ALIASES.get(key, fallback)
