from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ColumnDef:
    name: str
    sqlite_type: str
    postgres_type: str
    not_null: bool
    primary_key_position: int
    default: str | None


@dataclass(frozen=True)
class TableDef:
    name: str
    columns: tuple[ColumnDef, ...]

    @property
    def primary_key_columns(self) -> tuple[str, ...]:
        return tuple(
            column.name
            for column in sorted(self.columns, key=lambda item: item.primary_key_position)
            if column.primary_key_position
        )


def sqlite_catalog(sqlite_path: Path) -> list[TableDef]:
    """Inspect the existing SQLite runtime database for migration."""

    with sqlite3.connect(sqlite_path) as connection:
        connection.row_factory = sqlite3.Row
        rows = connection.execute(
            """SELECT name FROM sqlite_master
            WHERE type='table' AND name NOT LIKE 'sqlite_%'
            ORDER BY name"""
        ).fetchall()
        tables = []
        for row in rows:
            name = str(row["name"])
            columns = []
            for column in connection.execute(f"PRAGMA table_info({quote_sqlite_identifier(name)})"):
                sqlite_type = str(column["type"] or "TEXT")
                default = (
                    str(column["dflt_value"]) if column["dflt_value"] is not None else None
                )
                columns.append(
                    ColumnDef(
                        name=str(column["name"]),
                        sqlite_type=sqlite_type,
                        postgres_type=postgres_type(sqlite_type),
                        not_null=bool(column["notnull"]),
                        primary_key_position=int(column["pk"] or 0),
                        default=default,
                    )
                )
            tables.append(TableDef(name=name, columns=tuple(columns)))
        return tables


def generate_postgres_schema(tables: list[TableDef]) -> str:
    statements = [
        "-- Auto-generated by autoalpha.service.postgres_migration",
        "CREATE SCHEMA IF NOT EXISTS public;",
    ]
    for table in tables:
        column_lines = []
        for column in table.columns:
            pieces = [quote_pg_identifier(column.name), column.postgres_type]
            if column.not_null or column.primary_key_position:
                pieces.append("NOT NULL")
            if column.default is not None and _portable_default(column.default):
                pieces.append(f"DEFAULT {column.default}")
            column_lines.append(" ".join(pieces))
        if table.primary_key_columns:
            keys = ", ".join(quote_pg_identifier(key) for key in table.primary_key_columns)
            column_lines.append(f"PRIMARY KEY ({keys})")
        body = ",\n  ".join(column_lines)
        statements.append(
            f"CREATE TABLE IF NOT EXISTS {quote_pg_identifier(table.name)} (\n  {body}\n);"
        )
    return "\n\n".join(statements) + "\n"


def migrate_sqlite_to_postgres(
    *,
    sqlite_path: Path,
    postgres_url: str,
    truncate: bool = False,
    batch_size: int = 1000,
) -> dict[str, Any]:
    """Create matching PostgreSQL tables and copy SQLite rows.

    This intentionally avoids foreign keys and sequences in the first migration
    pass. AutoAlpha mostly addresses rows by explicit IDs or natural keys; exact
    constraint reconstruction can be layered on after the Store adapter is live.
    """

    try:
        import psycopg
    except ImportError as error:  # pragma: no cover - depends on optional runtime
        raise RuntimeError("psycopg is required for PostgreSQL migration") from error

    tables = sqlite_catalog(sqlite_path)
    ddl = generate_postgres_schema(tables)
    copied: dict[str, int] = {}
    with sqlite3.connect(sqlite_path) as source:
        source.row_factory = sqlite3.Row
        with psycopg.connect(postgres_url) as target, target.cursor() as cursor:
            cursor.execute(ddl)
            if truncate:
                for table in reversed(tables):
                    truncate_sql = (
                        f"TRUNCATE TABLE {quote_pg_identifier(table.name)} "
                        "RESTART IDENTITY CASCADE"
                    )
                    cursor.execute(truncate_sql)
            for table in tables:
                columns = [column.name for column in table.columns]
                if not columns:
                    copied[table.name] = 0
                    continue
                selected_columns = ", ".join(quote_sqlite_identifier(column) for column in columns)
                select_sql = (
                    f"SELECT {selected_columns} FROM {quote_sqlite_identifier(table.name)}"
                )
                insert_sql = (
                    f"INSERT INTO {quote_pg_identifier(table.name)} "
                    f"({', '.join(quote_pg_identifier(column) for column in columns)}) "
                    f"VALUES ({', '.join(['%s'] * len(columns))}) "
                    f"ON CONFLICT DO NOTHING"
                )
                count = 0
                rows = []
                for row in source.execute(select_sql):
                    rows.append(tuple(row[column] for column in columns))
                    if len(rows) >= max(1, int(batch_size)):
                        cursor.executemany(insert_sql, rows)
                        count += len(rows)
                        rows.clear()
                if rows:
                    cursor.executemany(insert_sql, rows)
                    count += len(rows)
                copied[table.name] = count
    return {
        "protocol": "AUTOALPHA_SQLITE_TO_POSTGRES_MIGRATION_V1",
        "sqlite_path": str(sqlite_path),
        "table_count": len(tables),
        "copied_rows": copied,
        "total_copied_rows": sum(copied.values()),
    }


def postgres_type(sqlite_type: str) -> str:
    normalized = sqlite_type.strip().upper()
    if "INT" in normalized:
        return "BIGINT"
    if any(token in normalized for token in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in normalized:
        return "BYTEA"
    return "TEXT"


def quote_sqlite_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def quote_pg_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _portable_default(default: str) -> bool:
    lowered = default.strip().casefold()
    return not ("datetime" in lowered or "strftime" in lowered)
